title: Lewis White
description: Data Science and Data Analytics - Projects

# Google Analytics
google_analytics: UA-215081080-1

#Added the theme
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/minimal@v0.2.0

#Added downloads
show_downloads: true
