title: Lewis White
description: Data science projects I have worked on to showcase a range of my skills in data science/data analysis.

# Google Analytics
google_analytics: UA-215081080-1

#Added the theme
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/slate@v0.2.0
