title: Lewis White
description: Some data science projects I have worked on in my spare time to showcase my skills in data science/data analysis.
theme: jekyll-theme-slate
# Additional configuration settings
