title: Lewis White - Data science projects
description: Several examples of different data science projects which I have worked on to showcase my skills in data science/analytics.
theme: jekyll-theme-slate
# Additional configuration settings
