title: Lewis White
description: Data science projects I have worked on to showcase a range of my skills in data science/data analysis.
theme: jekyll-theme-slate
# Additional configuration settings
# Google Analytics
google_analytics: G-8BKP64N4X7
