title: Lewis White
description: Data science projects I have worked on to showcase a range of my skills in data science/data analysis.
#Added the theme below instead of this
#theme: jekyll-theme-slate
# Additional configuration settings

#Added this to make the Google Analytics work
- theme: slate
+ remote_theme: jekyll/slate

  plugins:
+ - jekyll-remote-theme

# Google Analytics
google_analytics: UA-215081080-1
