title: Lewis White
description: Data science projects I have worked on to showcase a range of my skills in data science/data analysis.
#Added the theme below instead of this
#theme: jekyll-theme-slate
# Additional configuration settings
# Google Analytics
google_analytics: UA-215081080-1

#Added this to make the Google Analytics work
#- theme: slate
plugins:
  - jekyll-remote-theme
  
remote_theme: jekyll/slate
