title: Lewis White - Data science projects
description: Several examples of different data science projects which I have worked on to show my skills in data science and data analytics.
theme: jekyll-theme-slate
# Additional configuration settings
