title: Lewis White
description: Data science projects I have worked on in my spare time to showcase a range of my skills in data science/data analysis.
theme: jekyll-theme-slate
# Additional configuration settings
google_analytics: G-8BKP64N4X7
