title: Lewis White
description: Data Science / Data Analysis Projects

# Google Analytics
google_analytics: UA-215081080-1

#Added the theme
plugins:
  - jekyll-remote-theme

remote_theme: pages-themes/slate@v0.2.0
