title: Lewis White
description: Examples of different kinds of data science projects that I have worked on to showcase my skills in data science/data analysis.
theme: jekyll-theme-slate
# Additional configuration settings
